In [34]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn

In [35]:
df = pd.read_csv('emails.csv')  

In [36]:
df #1=spam

text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [37]:
df['spam'].value_counts()

0    4360
1    1368
Name: spam, dtype: int64

# Duplicates value remove

In [38]:
df.drop_duplicates(inplace = True)

In [39]:
df.shape

(5695, 2)

In [40]:
df['spam'].value_counts()

0    4327
1    1368
Name: spam, dtype: int64

In [41]:
#Null checked
df.isnull().sum()

text    0
spam    0
dtype: int64

# Separate x and y

In [42]:
x = df.text.values

In [43]:
y = df.spam.values

# Train Test Split

In [44]:
from sklearn.model_selection import train_test_split

In [45]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1) 

# Data Preprocessing Count Vectorizer

In [46]:
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
cv = CountVectorizer()
xtrain = cv.fit_transform(x_train)

In [48]:
xtrain.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Naive Bayes Classifiers

In [49]:
from sklearn.naive_bayes import MultinomialNB

In [50]:
MNG = MultinomialNB()

In [51]:
MNG.fit(xtrain, y_train) 

MultinomialNB()

In [52]:
xtest = cv.transform(x_test)

In [53]:
xtest.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [2, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [54]:
#accuracy
MNG.score(xtest, y_test)

0.9938542581211589

# Output 

In [55]:
emails = ['hey i am looking for machine learning tutorial in bangla language', 
          'hey you win an iphone x giveaway for free. please do the survey']

In [56]:
cv_emails = cv.transform(emails)

In [57]:
MNG.predict(cv_emails)

array([0, 1], dtype=int64)

In [58]:
# 0=Not spam,   1=Spam

# Performance

In [59]:
pred = MNG.predict(xtest)

In [60]:
pred

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [61]:
from sklearn.metrics import accuracy_score

In [62]:
accuracy_score(pred, y_test)

0.9938542581211589

# Confusion Matrix

In [63]:
from sklearn.metrics import confusion_matrix

In [64]:
confusion_matrix(pred, y_test)

array([[863,   4],
       [  3, 269]], dtype=int64)

In [65]:
from sklearn.metrics import classification_report

In [66]:
print(classification_report(pred, y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       867
           1       0.99      0.99      0.99       272

    accuracy                           0.99      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139



# k-Fold Cross Validation

In [76]:
# Data Preprocessing Count Vectorizer
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
x = cv.fit_transform(x)
x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [77]:
# if when we don to use train test
from sklearn.model_selection import cross_val_score

In [78]:
cv_score = cross_val_score(MNG, x,y, cv=10)

In [79]:
cv_score

array([0.98421053, 0.99122807, 0.98947368, 0.99122807, 0.99649123,
       0.98418278, 0.98242531, 0.99297012, 0.98945518, 0.99121265])

In [80]:
cv_score.mean()

0.989287762464157